title: My First Github Pages website look - Sample
author: Alric Mendonsa
email: alricm@github.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hey there ! So here i come with my initial github pages site with some small changes to be tested out

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
